// ---------- DATA (edit here; swap for real inventory later) ----------
const BRAND={wa:"6281228505388",waShow:"+62 81228505388",ig:"@dx_vault",email:"hello@dxtoysandhobbies.com",hours:"Monday–Saturday, 09:00–18:00 WIB"};
const COLS=[{n:"Diecast",slug:"diecast",d:"Hot Wheels, Mini GT, Pop Race, and more.",img:"/assets/collections/diecast.jpg",c:"#e63a2e",e:"🏎️"},
{n:"Trading Cards",slug:"trading-cards",d:"Pokémon, One Piece, and other collectible card products.",img:"/assets/collections/tcg.jpg",c:"#2457d6",e:"🃏"},
{n:"Toys & Collectibles",slug:"toys-collectibles",d:"Figures, toys, and collectible items.",img:"/assets/collections/toys.jpg",c:"#22a06b",e:"🧸"},
{n:"Accessories",slug:"accessories",d:"Display cases, sleeves, protectors, and hobby accessories.",img:"/assets/collections/accessories.jpg",c:"#c98f00",e:"🛡️"}];
const P=[
{id:1,name:"Pokémon Scarlet & Violet Booster Box",category:"Trading Cards",brand:"Pokémon",price:1299000,originalPrice:1399000,stock:12,status:"Available",badge:"Best Seller",sku:"DUMMY-TCG-001",description:"Sealed booster box for collectors and players.",image:"/assets/products/pokemon-box-01.jpg",slug:"pokemon-scarlet-violet-booster-box",tags:[]},
{id:2,name:"MINI GT Lamborghini Huracán",category:"Diecast",brand:"MINI GT",price:189000,originalPrice:199000,stock:7,status:"Available",badge:"New",sku:"DUMMY-DIECAST-001",description:"1:64 scale diecast collectible.",image:"/assets/products/mini-gt-01.jpg",slug:"mini-gt-lamborghini",tags:[]},
{id:3,name:"Hot Wheels Premium Set",category:"Diecast",brand:"Hot Wheels",price:299000,originalPrice:329000,stock:4,status:"Limited",badge:"Limited",sku:"DUMMY-DIECAST-002",description:"Premium diecast set for collectors.",image:"/assets/products/hot-wheels-premium.jpg",slug:"hot-wheels-premium-set",tags:[]},
{id:4,name:"Card Protector Premium 100 pcs",category:"Accessories",brand:"DX Accessories",price:39000,originalPrice:45000,stock:35,status:"Available",badge:"",sku:"DUMMY-ACC-001",description:"Protective sleeves for trading cards.",image:"/assets/products/card-protector.jpg",slug:"card-protector-100",tags:[]}];
const NEW_IDS=[1,2,3],BEST_IDS=[1,2,4];
const PRE=[{name:"Pokémon Booster Box — Upcoming Set",rel:"December 2026",price:1199000,dep:300000,status:"Open",d:"Limited pre-order allocation. Release date may change according to official distributor schedule.",img:"/assets/preorder/pokemon-upcoming.jpg"}];
const PROMO=[{t:"FREE SHIPPING WEEKEND",d:"Free shipping for selected orders.",p:"10–12 October 2026",c:"DXWEEKEND"},{t:"COLLECTOR DEAL",d:"Save more when purchasing selected bundles.",p:"",c:""}];
const WHY=[["Curated Products","We carefully select products worth adding to your collection.","✓","var(--red)"],["Collector Focused","Built for collectors, enthusiasts, and hobby communities.","★","var(--blue)"],["Safe Packaging","Every order is packed with care to help products arrive safely.","▣","var(--green)"],["Reliable Service","Fast response and transparent order information.","☎","#c98f00"]];
const FAQ=[["Are all products authentic?","Yes. We source products from trusted distributors and suppliers."],["Do you accept pre-orders?","Yes. Selected upcoming products are available for pre-order."],["Can I request specific products?","Yes. Contact us through WhatsApp or Instagram."],["How are orders packaged?","Products are packed according to their category and protection requirements."]];
const SHIP=["J&T Express","SiCepat","Anteraja"],PAY=["Bank Transfer","QRIS","E-Wallet","Marketplace Payment"];
